name: Update Publications

on:
  schedule:
    - cron: '0 0 2 * *'  # Run at midnight on the 2nd day of each month
  workflow_dispatch:  # Allow manual trigger

jobs:
  update-publications:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install scholarly pyyaml

      - name: Update publications
        env:
          SCHOLAR_ID: ${{ secrets.GOOGLE_SCHOLAR_ID }}
        run: |
          # Update the Scholar ID in the script
          sed -i "s/SCHOLAR_ID = \"\"/SCHOLAR_ID = \"$SCHOLAR_ID\"/" scripts/update_publications.py
          # Run the script
          python scripts/update_publications.py

      - name: Check for changes
        id: check_changes
        run: |
          git status --porcelain content/publication/
          echo "has_changes=$(git status --porcelain content/publication/ | wc -l)" >> $GITHUB_OUTPUT

      - name: Commit and push if there are changes
        if: steps.check_changes.outputs.has_changes != '0'
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add content/publication/
          git commit -m "Update publications from Google Scholar"
          git push
