name: Update Publications

on:
  schedule:
    - cron: '0 0 2 * *'  # Run at midnight on the 2nd day of each month
  workflow_dispatch:  # Allow manual trigger

jobs:
  update-publications:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      has_changes: ${{ steps.check_changes.outputs.has_changes }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install scholarly pyyaml requests Pillow tenacity

      - name: Update publications
        run: |
          python scripts/advanced_publication_script.py
        continue-on-error: true  # Continue even if script fails

      - name: Check for changes
        id: check_changes
        run: |
          git status --porcelain content/publication/
          echo "has_changes=$(git status --porcelain content/publication/ | wc -l)" >> $GITHUB_OUTPUT

      - name: Commit and push if there are changes
        if: steps.check_changes.outputs.has_changes != '0'
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add content/publication/
          git commit -m "Update publications from Google Scholar"
          git push

  deploy-site:
    needs: update-publications
    if: needs.update-publications.outputs.has_changes == '1'
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          user_name: 'GitHub Action'
          user_email: 'action@github.com'
          commit_message: ${{ github.event.head_commit.message }}
          full_commit_message: ${{ github.event.head_commit.message }}
